name: Republic
favicon: null
layout_spectrum: 0.6510354566853493
typography_spectrum: 0.5597970720846206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.11337822233326733
  lightness: 0.8173079211264849
  saturation: 0.673619870794937
  rhythmicContrast: 0.18567938008345664
purpose: []
